version: '3.4'

services:

  api:
    container_name: be-challenge-massis-api
    hostname: 'be-challenge-massis-api.com'
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    networks:
      - network
    depends_on:
      - db
    restart: on-failure:2
    env_file:
      - .env
    command: bash -c "alembic upgrade head && python -m server"

  db:
    container_name: be-challenge-massis-postgres
    hostname: 'be-challenge-massis-postgres.com'
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=football
    networks:
      - network

networks:
  network:
    driver: bridge
