version: '3.4'

services:
  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    networks:
      - network
    depends_on:
      - db
    restart: on-failure:2
    command: bash -c "python -m server"
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=challenge
    networks:
      - network
networks:
  network:
    driver: bridge
